import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFile, unlink } from 'node:fs/promises';
import { build } from 'esbuild';
import React from 'react';
import Renderer,{act} from 'react-test-renderer';

test('barber UI: exclusive views, real edit loading, discard guard, validation and one save',async t=>{
  const target=new URL(`./.barber-ui-${process.pid}.mjs`,import.meta.url);
  const bundle=await build({entryPoints:['src/admin/BarberManager.jsx'],bundle:true,write:false,platform:'node',format:'esm',packages:'external',jsx:'automatic',define:{'import.meta.env':'{}'}});
  await writeFile(target,bundle.outputFiles[0].text);t.after(()=>unlink(target));
  const {default:Manager}=await import(target.href);
  const previous=globalThis.window;
  let confirmResult=false;
  globalThis.window={confirm:()=>confirmResult,addEventListener(){},removeEventListener(){}};
  t.after(()=>{globalThis.window=previous;});
  const barber={id:'10000000-0000-0000-0000-000000000099',name:'Profissional Existente',active:true,booking_enabled:false,public_booking_key:'public-key',description:'Descrição real',minimum_notice_minutes:90};
  const snapshot={barber,hours:[],breaks:[],links:[],overrides:[],blocks:[]};
  const data={barbers:[barber],barber_hours:[],barber_breaks:[],barber_services:[],barber_date_overrides:[],schedule_blocks:[],services:[],photo_urls:{}};
  const calls=[];let finishSave;
  const api=async(action,input)=>{calls.push({action,input});if(action==='barber_editor_snapshot')return snapshot;if(action==='save_barber_profile')return new Promise(resolve=>{finishSave=resolve;});throw new Error('Unexpected operation');};
  const guard={current:()=>true};let updated=0;let view;
  await act(async()=>{view=Renderer.create(React.createElement(Manager,{data,api,guard,onChanged:async()=>updated++,onDeactivate(){}}));});
  t.after(()=>{act(()=>view.unmount());});
  const text=node=>node.children.map(c=>typeof c==='string'?c:text(c)).join('');
  const button=label=>view.root.findAllByType('button').find(n=>text(n)===label);
  assert.equal(view.root.findAllByType('form').length,0);
  await act(async()=>button('+ Novo barbeiro').props.onClick());
  assert.equal(calls.length,0,'opening new form persists nothing');
  assert.equal(view.root.findAllByType('article').length,0);
  assert.equal(view.root.findAllByType('form').length,1);
  const nameInput=()=>view.root.findAllByType('input').find(n=>n.props.minLength===2);
  await act(async()=>nameInput().props.onChange({target:{value:'Novo Profissional'}}));
  await act(async()=>button('Cancelar').props.onClick());
  assert.equal(view.root.findAllByType('form').length,1,'cancel requires discard confirmation');
  assert.equal(guard.current(),false,'sidebar navigation shares discard protection');
  confirmResult=true;await act(async()=>button('Cancelar').props.onClick());
  assert.equal(view.root.findAllByType('form').length,0);assert.equal(calls.length,0);
  await act(async()=>button('Editar').props.onClick());
  assert.equal(calls[0].action,'barber_editor_snapshot');assert.equal(nameInput().props.value,barber.name);
  assert.equal(view.root.findAllByType('textarea')[0].props.value,barber.description);
  assert.equal(view.root.findAllByType('article').length,0);
  assert.ok(button('Salvar alterações'));assert.ok(!button('Salvar barbeiro'));
  const form=view.root.findByType('form');
  await act(async()=>nameInput().props.onChange({target:{value:'X'}}));
  await act(async()=>form.props.onSubmit({preventDefault(){}}));
  assert.equal(calls.length,1,'invalid edit is not sent');
  await act(async()=>nameInput().props.onChange({target:{value:'Nome atualizado'}}));
  let pending;
  await act(async()=>{pending=form.props.onSubmit({preventDefault(){}});});
  await act(async()=>{form.props.onSubmit({preventDefault(){}});});
  assert.equal(calls.filter(c=>c.action==='save_barber_profile').length,1);
  assert.deepEqual(calls[1].input.expected,snapshot);
  assert.equal(calls[1].input.profile.minimum_notice_minutes,90);
  assert.equal(guard.current(),false,'cannot leave while saving');
  await act(async()=>{finishSave({id:barber.id});await pending;});
  assert.equal(updated,1);assert.equal(view.root.findAllByType('form').length,0);
  assert.equal(view.root.findAllByType('article').length,1);
});
